#!/bin/bash
set -e

echo "🚀 Configurando ambiente Zsh..."

# Diretórios
ZSH_DIR="$HOME/.zsh"
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

# Criar diretório .zsh
mkdir -p "$ZSH_DIR"

# Instalar Zinit se não existir
if [ ! -d "$ZINIT_HOME" ]; then
    echo "📦 Instalando Zinit..."
    mkdir -p "$(dirname $ZINIT_HOME)"
    git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

# Criar .zshrc
ZSHRC_CONTENT='#!/bin/zsh

# ============================================
# Zinit Configuration
# ============================================

# Caminho do Zinit
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
source "${ZINIT_HOME}/zinit.zsh"

# Carregar Zinit
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# ============================================
# Powerlevel10k
# ============================================

# Instalar e carregar Powerlevel10k instantaneamente
zinit ice depth=1; zinit light romkatv/powerlevel10k

# ============================================
# Plugins Zinit
# ============================================

# Zsh syntax highlighting
zinit light zsh-users/zsh-syntax-highlighting

# Zsh autosuggestions
zinit light zsh-users/zsh-autosuggestions

# Zsh completions
zinit light zsh-users/zsh-completions

# History search
zinit light zsh-users/zsh-history-substring-search

# FZF integration
zinit light Aloxaf/fzf-tab

# ============================================
# Atalhos e Configurações
# ============================================

# Histórico
HISTSIZE=10000
SAVEHIST=10000
HISTFILE="$HOME/.zsh_history"
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE

# Comportamento
setopt AUTO_CD
setopt EXTENDED_GLOB
setopt NO_CASE_GLOB
setopt NUMERIC_GLOB_SORT

# Key bindings
bindkey "^[[A" history-substring-search-up
bindkey "^[[B" history-substring-search-down
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line
bindkey "^[[3~" delete-char

# ============================================
# Aliases - Ferramentas Modernas
# ============================================

# LS -> Eza (exa moderno)
alias ls="eza --icons --group-directories-first"
alias ll="eza --icons --group-directories-first -la"
alias la="eza --icons --group-directories-first -a"
alias lt="eza --icons --group-directories-first --tree --level=2"
alias llt="eza --icons --group-directories-first -la --tree --level=2"

# Cat -> Bat
alias cat="bat --paging=never"
alias less="bat"
alias bathelp="bat --plain --language=help"
help() { "$@" --help 2>&1 | bathelp; }

# Find -> Fd
alias find="fd"
alias fd="fd --hidden --follow --exclude=.git --exclude=node_modules"

# Grep -> Ripgrep
alias grep="rg"

# Git com Delta
alias gdiff="git diff"
alias glog="git log --oneline --graph --decorate"

# Docker
alias d="docker"
alias dc="docker-compose"
alias dps="docker ps --format \"table {{.Names}}\\t{{.Status}}\\t{{.Ports}}\""

# Node/NPM
alias nr="npm run"
alias ni="npm install"
alias nid="npm install --save-dev"
alias nrs="npm run start"
alias nrd="npm run dev"
alias nrb="npm run build"
alias nrt="npm run test"

# Utilitários
alias ..="cd .."
alias ...="cd ../.."
alias mkdir="mkdir -p"
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"
alias cls="clear"
alias reload="source ~/.zshrc"

# ============================================
# FZF Configuration
# ============================================

export FZF_DEFAULT_OPTS="
  --height 50%
  --layout=reverse
  --border
  --preview \"bat --color=always --style=numbers --line-range=:500 {}\"
  --preview-window=right:50%
  --bind \"ctrl-u:preview-half-page-up\"
  --bind \"ctrl-d:preview-half-page-down\"
"

# ============================================
# Bat Configuration
# ============================================

export BAT_THEME="Dracula"
export BAT_STYLE="numbers,changes,header"
export MANPAGER="sh -c \"col -bx | bat -l man -p\""

# ============================================
# Node Environment
# ============================================

export PATH="./node_modules/.bin:$PATH"

# ============================================
# Completions
# ============================================

autoload -U compinit && compinit
zstyle ":completion:*" menu select
zstyle ":completion:*" matcher-list "m:{a-zA-Z}={A-Za-z}"

# FZF Tab
zstyle ":fzf-tab:complete:cd:*" fzf-preview "eza --icons -1 --color=always $realpath"
zstyle ":fzf-tab:complete:ls:*" fzf-preview "bat --color=always $realpath"

# ============================================
# Load Powerlevel10k Config
# ============================================

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
'

# Salvar .zshrc
echo "$ZSHRC_CONTENT" > "$HOME/.zshrc"

# Criar .p10k.zsh (configuração mínima do Powerlevel10k)
P10K_CONTENT='# Generated by Powerlevel10k configuration wizard on 2024.
# Tipo de prompt: Lean - minimalista e rápido

# Configuração de cores
() {
  emulate -L zsh -o extended_glob

  # Tema: Dark
  local black="0"
  local red="1"
  local green="2"
  local yellow="3"
  local blue="4"
  local magenta="5"
  local cyan="6"
  local white="7"
  local grey="8"

  # Esquema de cores
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    dir
    vcs
    prompt_char
  )

  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status
    command_execution_time
    background_jobs
    node_version
    time
  )

  # Dir
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=$cyan
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=$cyan
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=$blue
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=
  typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=v3

  # Git
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=$green
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=$yellow
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=$green
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=$red
  typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=$grey
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON="\uF126 "
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON="?"

  # Prompt char
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=$green
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND=$red
  typeset -g POWERLEVEL9K_PROMPT_CHAR_CONTENT_EXPANSION="❯"

  # Status
  typeset -g POWERLEVEL9K_STATUS_OK=false
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=$red
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=$red

  # Tempo de execução
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=$yellow
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=1

  # Background jobs
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=$magenta
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false

  # Node.js
  typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=$green
  typeset -g POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true

  # Time
  typeset -g POWERLEVEL9K_TIME_FOREGROUND=$grey
  typeset -g POWERLEVEL9K_TIME_FORMAT="%H:%M"
  typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false

  # Separadores
  typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=" "
  typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=" "
  typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=""
  typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=""
  typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_FIRST_SEGMENT_END_SYMBOL=""
  typeset -g POWERLEVEL9K_EMPTY_LINE_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=""
}
'

# Salvar .p10k.zsh
echo "$P10K_CONTENT" > "$HOME/.p10k.zsh"

echo "✅ Zsh configurado com sucesso!"
echo ""
echo "🎨 Ferramentas instaladas:"
echo "   • Zsh (shell)"
echo "   • Zinit (plugin manager)"
echo "   • Powerlevel10k (theme)"
echo "   • zsh-syntax-highlighting"
echo "   • zsh-autosuggestions"
echo "   • zsh-completions"
echo ""
echo "🦀 Ferramentas Rust:"
echo "   • bat (cat melhorado)"
echo "   • eza (ls moderno)"
echo "   • fd (find moderno)"
echo "   • ripgrep (grep moderno)"
echo "   • delta (git diff melhorado)"
echo ""
echo "⚡ Aliases configurados:"
echo "   ls -> eza, cat -> bat, find -> fd, grep -> rg"
echo ""
echo "🔧 Para aplicar as mudanças, execute: source ~/.zshrc"
